name: test-build.yml
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v4

      - name: set-up-node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install-deps
        run: npm install